config/routes.rb
Assosiation::Application.routes.draw do

  resources :colony
  resources :house
  resources  :flat
  resources  :family

   root :to => 'colony#index'

end

app/models/colony.rb
class Colony < ActiveRecord::Base
   attr_accessible :name, :city
  has_many :houses
end

app/models/family.rb
class Family < ActiveRecord::Base
   attr_accessible :members, :cast, :salary,:flat_id
   belongs_to :flat
end

app/models/flat.rb
class Flat < ActiveRecord::Base
  attr_accessible :rooms, :colour
  belongs_to :house
  has_one :family
end

app/models/house.rb
class House < ActiveRecord::Base
  attr_accessible :h_name, :h_no, :Colony_id
  belongs_to :colony
  validates :h_name,:h_no, :presence =>'true'


  has_many :flats
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/colony_controller.rb
class ColonyController < ApplicationController

  def index
    @col=Colony.all
  end

  def new
    @col=Colony.new
  end

  def create
    @col=Colony.new(params[:colony])

    if @col.save
      redirect_to :action=>'index'
      flash[:notice] = "New Colony created"
    else
      render 'new'
    end
  end

  def edit
    @col=Colony.find(params[:id])
  end

  def update
    @col=Colony.find(params[:id])
    if @col.update_attributes(params[:colony])
      redirect_to :action=>'index'
    else
      render 'edit'
    end
  end

  def show
    @col=Colony.find(params[:id])
  end

  def  destroy
    @col=Colony.find(params[:id])
    if @col.delete
      redirect_to :action=>'index'
    end
  end

end

app/controllers/family_controller.rb
class FamilyController < ApplicationController

    def index
      @flt=Flat.find(params[:id])

      @fml=@flt.family
    end

    def new
      @flt=Flat.find(params[:id])

      @fml=@flt.build_family
    end
    #:flat_id=>@fml.flat_id
    def create
      @flt=Flat.find(params[:flat_id])
      @fml=@flt.build_family(params[:family])

      if @fml.save
        redirect_to :action=>'index', :id=>@flt.id
      else
        render 'new'
      end
    end

    def edit

      @fml=Family.find(params[:id])
    end

    def update
      @fml=Family.find(params[:id])
      @flt=@fml.flat
      if @fml.update_attributes(params[:family])
        redirect_to :action=>'index', :id=>@flt.id
      else
        render 'edit'
      end
    end

    def show

      @fml=Family.find(params[:id])
    end

    def  destroy
      #@flt=Flat.find(params[:id])
      #@fml=@flt.family
      @fml=Family.find(params[:id])
      @flt=@fml.flat
      if @fml.delete
        redirect_to :action=>'index', :id=>@flt.id
      end
    end





end

app/controllers/flat_controller.rb
class FlatController < ApplicationController
    def index
      @hou=House.find(params[:id])
      @flt=@hou.flats.all
    end

    def new
      @hou=House.find(params[:id])
      @flt=@hou.flats.new
    end

    def create
      @hou=House.find(params[:id])
      @flt=@hou.flats.create(params[:flat])

      if @flt.save
        redirect_to :action=>'index', :id=>@hou.id
      else
        render 'new'
      end
    end

    def edit
      @flt=Flat.find(params[:id])
      @hou=@flt.house
    end

    def update
      @flt=Flat.find(params[:id])
      @hou=@flt.house
      if @flt.update_attributes(params[:flat])
        redirect_to :action=>'index', :id=>@hou.id
      else
        render 'edit'
      end
    end

    def show
      @flt=Flat.find(params[:id])
    end

    def  destroy
      @flt=Flat.find(params[:id])
      @hou=@flt.house
      if @flt.delete
        redirect_to :action=>'index', :id=>@hou.id
      end
    end

  end

app/controllers/house_controller.rb
  class HouseController < ApplicationController

  def index
    @col=Colony.find(params[:id])
    @hou=@col.houses.all
  end

  def new
    @col=Colony.find(params[:id])
    @hou=@col.houses.new
  end

  def create
    @col=Colony.find(params[:id])
    @hou=@col.houses.create(params[:house])

    if @hou.save
      redirect_to :action=>'index', :id=>@col.id
    else
      flash[:notice]='please fill correctly, h_no integer  '
      render 'new'
    end
  end


  def edit
    @hou=House.find(params[:id])
    @col=@hou.colony
  end

  def update
    @hou=House.find(params[:id])
    @col=@hou.colony
    if @hou.update_attributes(params[:house])
      redirect_to :action=>'index', :id=>@col.id
    else
      flash[:notice]='please fill in H-NO integer'
      render 'edit'
    end
  end

  def show
    @hou=House.find(params[:id])
  end

  def  destroy
    @hou=House.find(params[:id])
    @col=@hou.colony
    if @hou.delete
      redirect_to :action=>'index', :id=>@col.id
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colony_helper.rb
module ColonyHelper
end

app/helpers/family_helper.rb
module FamilyHelper
end

app/helpers/flat_helper.rb
module FlatHelper
end

app/helpers/house_helper.rb
module HouseHelper
end

app/views/colony/edit.html.haml
%h1 Editing
= form_for @col do |col|
  %b Name:
  = col.text_field:name
  %br/
  %b City:
  =col.text_field:city
  %br/
  = col.submit

app/views/colony/index.html.haml
=flash[:notice]
%h1 Colony_Listing
%table{ :align=>"center", :border=>"1"}
  %tr
    %th Colony_Name
    %th City_name
    %th Associate
    %th  show
    %th  update

  - @col.each do |col|
    %tr
      %td
        =col.name
      %td
        =col.city
      %td=link_to 'houses',:controller=>'house',:action=>'create',:id=>col.id
      %td= link_to image_tag("Show.png",:width=>20) ,col
      %td= link_to image_tag("update.png", :width=>20),edit_colony_path(col)


= link_to 'new entry', new_colony_path
%br/

app/views/colony/new.html.haml
%h1 Entry
= form_for @col,:url=>{:action=>'create'} do |col|
  =col.label :Name
  =col.text_field:name
  %br/
  =col.label :City
  =col.text_field:city
  %br/
    
  = col.submit "save"

app/views/colony/show.html.haml
%h1 Details

%b Name:
= @col.name
%br/


%b City:
= @col.city
%br

= link_to 'index',colony_index_path

app/views/family/edit.html.haml
%h1 edit
= form_for @fml do |fml|
  %b Members
  = fml.text_field :members
  %br/
  %b Cast
  = fml.select(:cast,["Hindu","Muslim","Sikh","Christians"],:prompt=>'select',:class=>'space-button quote_request_form')
  %br/
  .field
    %b= fml.label :Family_Income
    %br/
    = fml.radio_button :salary, "low"
    10000 to 20000
    %br/
    = fml.radio_button :salary, "medium"
    21000 to 30000
    %br/
    = fml.radio_button :salary, "high"
    Above 300000
  = fml.submit

app/views/family/index.html.haml
%h1 Family_Listing
%table{:align => "center",:border => "1" }
  %tr
    %th Members
    %th Salary
    %th Cast
    %th Show
    %th

  - if @fml
    %tr
      %td
        =@fml.members
      %td
        =@fml.salary
      %td
        =@fml.cast
      %td
        =link_to image_tag("Show.png",:width=>20),@fml
      %td
        =link_to image_tag("update.png", :width=>20),edit_family_path(@fml)
= link_to 'new',:controller=>'family',:action=>'new',:id=>@flt.id
%br/
= link_to 'colony_index', colony_index_path

app/views/family/new.html.haml
%h1 new
= form_for @fml, :url=>{:action=>'create',:flat_id=>@fml.flat_id} do |fml|
  %b Members
  = fml.text_field :members
  %br/
  %b Cast
  = fml.select(:cast,["Hindu","Muslim","Sikh","Christians"],:prompt=>'select',:class=>'space-button quote_request_form')
  %br/
  .field
    %b= fml.label :Family_Income
    %br/
    = fml.radio_button :salary, "low"
    10000 to 20000
    %br/
    = fml.radio_button :salary, "medium"
    21000 to 30000
    %br/
    = fml.radio_button :salary, "high"
    Above 300000
  = fml.submit

app/views/family/show.html.haml
%h1 show

%b Members:
= @fml.members
%br/


%b Salary:
= @fml.salary
%br/


%b Cast:
= @fml.cast

app/views/flat/edit.html.haml
%h1 edit
= form_for @flt do |flat|
   %b Flat-room:
   = flat.text_field :rooms
   %br/

   %b Flat-colour:
   = flat.text_field :colour
   %br/
   = flat.submit

app/views/flat/index.html.haml
%h1 Flat_Listing


%table{:align=>"center", :border=>"1"}
  %tr
    %th Color
    %th Rooms
    %th Associate
    %th Show
    %th


  - @flt.each do |flat|
    %tr
      %td
        =flat.colour
      %td
        =flat.rooms
      %td
        =link_to'families',:controller=>'family',:action=>'index',:id=>flat.id
      %td
        =link_to image_tag("Show.png",:width=>20),flat
      %td
        =link_to  image_tag("update.png", :width=>20), edit_flat_path(flat)

= link_to 'new',:controller=>'flat',:action=>'new',:id=>@hou.id
= link_to 'colony_index', colony_index_path
        

app/views/flat/new.html.haml
%h1 New
= form_for (@flt),:url=>{:action=>'create',:id=>@hou.id} do |flat|
   %b No of rooms:
   = flat.text_field :rooms
   %br/
   %b Flat-color.
   =flat.text_field :colour
   %br/
   = flat.submit


= link_to 'house_index', house_index_path

app/views/flat/show.html.haml
%h1 Details
%b Rooms
= @flt.rooms
%br/
%b Colour
= @flt.colour

app/views/house/edit.html.haml
%h1 edit

= form_for @hou do |house|
  %b House-Name:
  = house.text_field :h_name
  %br/

  %b House-No.
  =house.text_field :h_no
  %br/
  = house.submit

app/views/house/index.html.haml
%h1 House_Listing

%table{:align=> "center", :border=> "1"}
  %tr
    %th House_name
    %th House_no.
    %th Associate
    %th Show
    %th  Update


  - @hou.each do |house|
    %tr
      %td= house.h_name
      %td= house.h_no
      %td= link_to 'flats', :controller=>'flat',:action=>'index',:id=>house.id
      %td= link_to image_tag("Show.png",:width=>20), house
      %td= link_to image_tag("update.png",:width=>20), edit_house_path(house)


= link_to'new',:controller=>'house',:action=>'new',:id=>@col.id
%br/
= link_to 'colony_index',colony_index_path

app/views/house/new.html.haml
%h1 New
=flash[:notice]
= form_for (@hou),:url=>{:action=>'create',:id=>@col.id} do |house|
  %b House-Name:
  = house.text_field :h_name
  %br/
  %b House-No.
  = house.text_field :h_no
  %br/
  = house.submit

app/views/house/show.html.haml
%h1 details
%b House-Name:
= @hou.h_name
%br/
%b House-No:
= @hou.h_no
%br/
= link_to 'house_index', house_index_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assosiation</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body style="background-color:#ddffdd;">
<div id="header" style="background-color:#CCCCA3; height: 50px; top:0px; margin: 0;  ">
  <h2 align= "center"><marquee>Welcome in linked Association application</marquee></h2>
</div>
<%= yield %>

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<div id="footer" style="background-color:#CCCCA3;clear:both;text-align:center;height:80px;margin:0px; "> <br/>
  Copyright © prashantmishra.com</div>


</body>
</html>